### ISSUE TITLE
Mettre davantage en avant le point median dans le bouton "copier le point median"

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#22]
Salut :)

Suite à un échange sur cette issue #9, on aimerait grossir le rendu visuel du point.

idées en vrac pour avoir le bon rendu:
- augmenter la font-size (mais on ne veut pas changer la taille total du bouton)
- scale le content (mais on ne veut pas changer la taille total du bouton)
- utiliser un background image (genre venant de icon)
- utiliser un charactère unicode en forme de gros cercle
- dessiner un cercle en css:

```css
#copyPoint {
  background-image: radial-gradient(10px circle at center, var(--form-text) 50%, transparent 51%)
}
```

bref, à expérimenter :)
